/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of SSLConn.xs. Do not edit this file, edit SSLConn.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "SSLConn.xs"
#include "module.h"

/* TODO


Purple::Ssl::Connection
purple_ssl_connect(account, host, port, func, error_func, data)
	Purple::Account account
	const char *host
	int port
	PurpleSslInputFunction func
	PurpleSslErrorFunction error_func

void
purple_ssl_input_add(gsc, func, data)
	Purple::Ssl::Connection gsc
	Purple::SslInputFunction func

Purple::Ssl::Connection
purple_ssl_connect_fd(account, fd, func, error_func, data)
	Purple::Account account
	int fd
	PurpleSslInputFunction func
	PurpleSslErrorFunction error_func

*/

#line 38 "SSLConn.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 90 "SSLConn.c"

XS(XS_Purple__SSL_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SSL_close)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gsc");
    {
	Purple__Ssl__Connection	gsc = purple_perl_ref_object(ST(0));

	purple_ssl_close(gsc);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SSL_get_ops); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SSL_get_ops)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Ssl__Ops	RETVAL;

	RETVAL = purple_ssl_get_ops();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Ssl::Ops");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SSL_is_supported); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SSL_is_supported)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	gboolean	RETVAL;

	RETVAL = purple_ssl_is_supported();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SSL_read); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SSL_read)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "gsc, buffer, len");
    {
	Purple__Ssl__Connection	gsc = purple_perl_ref_object(ST(0));
	void *	buffer = INT2PTR(void *,SvIV(ST(1)));
	size_t	len = (size_t)SvUV(ST(2));
	size_t	RETVAL;
	dXSTARG;

	RETVAL = purple_ssl_read(gsc, buffer, len);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__SSL_set_ops); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SSL_set_ops)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ops");
    {
	Purple__Ssl__Ops	ops = purple_perl_ref_object(ST(0));

	purple_ssl_set_ops(ops);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SSL_write); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SSL_write)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "gsc, buffer, len");
    {
	Purple__Ssl__Connection	gsc = purple_perl_ref_object(ST(0));
	void *	buffer = INT2PTR(void *,SvIV(ST(1)));
	size_t	len = (size_t)SvUV(ST(2));
	size_t	RETVAL;
	dXSTARG;

	RETVAL = purple_ssl_write(gsc, buffer, len);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__SSL); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__SSL)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Purple::SSL::close", XS_Purple__SSL_close, file, "$");
        (void)newXSproto_portable("Purple::SSL::get_ops", XS_Purple__SSL_get_ops, file, "");
        (void)newXSproto_portable("Purple::SSL::is_supported", XS_Purple__SSL_is_supported, file, "");
        (void)newXSproto_portable("Purple::SSL::read", XS_Purple__SSL_read, file, "$$$");
        (void)newXSproto_portable("Purple::SSL::set_ops", XS_Purple__SSL_set_ops, file, "$");
        (void)newXSproto_portable("Purple::SSL::write", XS_Purple__SSL_write, file, "$$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

